<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PDF</name>
   <tag></tag>
   <elementGuidId>6540f4b7-269a-431e-b5c1-20362823ee28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnDownloadCvPdf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnDownloadCvPdf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; PDF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ce384b7-c7c6-40b4-9c27-971a44c5f47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDownloadCvPdf</value>
      <webElementGuid>96de3d5d-03b9-4bf9-8548-9a7c0170e915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.cv-me.metrodataacademy.id/mitra/app/download?mitraUserId=UH185</value>
      <webElementGuid>3f577142-4176-4178-9560-bc8191947aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>647b7373-3bd1-4f56-a381-54f8a6bf559d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>714f895b-6027-456b-a296-6cac834765be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>1139ece5-35ff-44dc-8605-647d77d6e246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>downloadCv('pdf')</value>
      <webElementGuid>e5945ee5-8c8c-4f65-99e6-d57f42f27ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  PDF</value>
      <webElementGuid>2cba8791-d48c-4a16-8f3c-c3325d631e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDownloadCvPdf&quot;)</value>
      <webElementGuid>c52bee32-143f-4afb-abe9-a3e78fe5ae61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnDownloadCvPdf']</value>
      <webElementGuid>c0873c68-66d4-417a-8612-7b11f03f8e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalDownload']/div/div/div[2]/a</value>
      <webElementGuid>727dce6e-797f-4881-a826-44208dd84816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PDF')]</value>
      <webElementGuid>ba79d3f9-6972-4ed8-bb83-9f5af4841d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Unduh CV'])[1]/following::a[1]</value>
      <webElementGuid>0902e301-92a2-46cc-8ff8-4556ca64f959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.cv-me.metrodataacademy.id/mitra/app/download?mitraUserId=UH185')]</value>
      <webElementGuid>3a565019-398d-4788-aacb-830487e456db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/a</value>
      <webElementGuid>2750ead8-f79b-4515-b2ed-9939831d5172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnDownloadCvPdf' and @href = 'https://dev.cv-me.metrodataacademy.id/mitra/app/download?mitraUserId=UH185' and (text() = '  PDF' or . = '  PDF')]</value>
      <webElementGuid>6dbbe93f-2619-4a47-a38a-d2da72348b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
