<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Word</name>
   <tag></tag>
   <elementGuidId>2d63822c-3b66-4872-865e-5c0b4c806beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnDownloadCvWord']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnDownloadCvWord</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Word&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>657e0f55-66f2-42a3-b239-f503fcea5af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDownloadCvWord</value>
      <webElementGuid>f7e6f745-526a-4499-9f87-fb2e69393cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.cv-me.metrodataacademy.id/mitra/app/download/docx?mitraUserId=UH185</value>
      <webElementGuid>6b907c9d-1fde-4a1c-977c-ef6dd80bae4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>186da981-f1eb-45e1-8126-c9a3b67fe002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>b0c4153f-919f-4d3b-a874-3e672e0b905e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>923ab9cc-f551-46f0-b329-d18152c96ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>downloadCv('word')</value>
      <webElementGuid>9875d9fe-3899-4c15-b4a7-4399ddc08e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Word</value>
      <webElementGuid>8d5e8289-dfe6-4cd6-9ed9-71020286289d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDownloadCvWord&quot;)</value>
      <webElementGuid>1d4af927-11f9-41a2-8f6c-e031532eb141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnDownloadCvWord']</value>
      <webElementGuid>d8a712b3-4f73-4cc0-b92d-9fbc7ceebb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalDownload']/div/div/div[2]/a[2]</value>
      <webElementGuid>b54fd001-5532-42db-8651-696bf6d528e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Word')]</value>
      <webElementGuid>2c1743c4-0aad-4b53-bc11-2fd2b002a135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/following::a[1]</value>
      <webElementGuid>e39db83b-4076-448d-983e-3d49e7341795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Word']/parent::*</value>
      <webElementGuid>e5422b8d-928d-48e3-a088-050c49e4af00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.cv-me.metrodataacademy.id/mitra/app/download/docx?mitraUserId=UH185')]</value>
      <webElementGuid>62301694-2a27-4c6f-b2a3-1e2770045448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>37b5f042-9690-4abd-b4c6-80420c943368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnDownloadCvWord' and @href = 'https://dev.cv-me.metrodataacademy.id/mitra/app/download/docx?mitraUserId=UH185' and (text() = ' Word' or . = ' Word')]</value>
      <webElementGuid>cb9dd516-2978-412c-8978-1c329bee4aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
