<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gambar</name>
   <tag></tag>
   <elementGuidId>48d08710-5396-4227-8dda-96a5a58de5a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-sc']/div/div/div/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nPDzT.T3FoJb > div.YmvwI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hdtb-sc >> internal:role=link[name=&quot;Gambar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>034aea21-8c55-418c-9bde-94c55adfdef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>bVqjv</value>
      <webElementGuid>b1a8ebad-db57-4f0a-8794-0dec00b33efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>YmvwI</value>
      <webElementGuid>1a59eeaa-ad78-4505-94e0-275234a2fe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gambar</value>
      <webElementGuid>72e2e05a-72dc-42ad-bdb6-b9c3fcb9d23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-sc&quot;)/div[@class=&quot;PHj8of J1AhHd&quot;]/div[@class=&quot;qogDvd&quot;]/div[@class=&quot;crJ18e&quot;]/div[1]/div[2]/a[@class=&quot;nPDzT T3FoJb&quot;]/div[@class=&quot;YmvwI&quot;]</value>
      <webElementGuid>45d2a51f-0e19-4d3c-a154-cf737e14bba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-sc']/div/div/div/div/div[2]/a/div</value>
      <webElementGuid>c5f02480-e09a-4f8d-ad6b-c26eeaf2bb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::div[2]</value>
      <webElementGuid>790e8f34-542e-4fed-b1c8-c68e3ebf207e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter dan Topik'])[1]/following::div[8]</value>
      <webElementGuid>56b7fe70-a9bb-4326-83b0-ac242abb570c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping'])[1]/preceding::div[1]</value>
      <webElementGuid>a232c57d-d124-47dd-8fc5-ca9e06aea13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/preceding::div[3]</value>
      <webElementGuid>baac203f-6c87-4c53-811e-106968ba7c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gambar']/parent::*</value>
      <webElementGuid>3ea2834d-22ef-4bab-9f42-f63d08d5cced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>bb7a95ab-b46d-4a0c-8ad7-40dd80f3f48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gambar' or . = 'Gambar')]</value>
      <webElementGuid>d20510e0-50ca-4b28-ba7b-aed72bd5a9ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
