<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Deskripsi Project_note-editable</name>
   <tag></tag>
   <elementGuidId>a3f5e7cf-c35c-4250-9405-6462fd4ae9e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseProject--1']/div[3]/div/div/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapseProject--1 > div.row > div.form-group.col-md-12 > div.note-editor.note-frame.panel.panel-default > div.note-editing-area > div.note-editable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^a$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d95804c-a50e-4341-8c06-0236d49230f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editable</value>
      <webElementGuid>2fd28313-ba9f-4025-ad66-8699dc9f3164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7184907-37e0-44ad-945e-c41ed62eca25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>01f984c5-af83-4309-a1ee-add85ceecd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e1f5920-0655-4b62-ac02-73b074a6f644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>406e1a05-da09-4738-b9e8-0244eaff5483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1039ddd0-973a-45ad-8f9b-e6ae67a4b77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseProject--1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-md-12&quot;]/div[@class=&quot;note-editor note-frame panel panel-default&quot;]/div[@class=&quot;note-editing-area&quot;]/div[@class=&quot;note-editable&quot;]</value>
      <webElementGuid>97ee1eee-8aeb-4b79-ae75-76456cdf090d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseProject--1']/div[3]/div/div/div[3]/div[2]</value>
      <webElementGuid>782da2d2-76e0-44ab-94b3-90bcacc7269f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Project'])[1]/following::div[16]</value>
      <webElementGuid>bbda9b1b-55f7-418c-b366-d438beee6a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lembaga / Perusahaan'])[1]/following::div[18]</value>
      <webElementGuid>d6f0921b-ee6a-4df6-b3a0-8fcaefa115a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert Link'])[3]/preceding::div[6]</value>
      <webElementGuid>7f2be91a-d64a-49ba-aa7d-762936482538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[2]</value>
      <webElementGuid>dfc81cdc-4e00-4e82-a6c1-404b1c499859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
