<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_(Anda belum mengisi)_fa mt-1 text-primary pl-4</name>
   <tag></tag>
   <elementGuidId>9fc03054-52b5-4c1b-ab87-9ec76463d7fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='talentTbl']/tr/td/div/div[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-pencil-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Profile Image DINDA DWI - Programming  &quot;i] >> a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>422a0a07-75c8-4274-a90c-90b1d312122a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-square</value>
      <webElementGuid>d4a19b8a-f996-4356-97d0-3187ce2c1e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60d5753b-a9f0-4186-b36d-1c5b2ae75dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;talentTbl&quot;)/tr[1]/td[1]/div[@class=&quot;card rounded-5 talent-list-card my-1 mx-1&quot;]/div[@class=&quot;row justify-content-end align-items-center mr-3&quot;]/a[@class=&quot;btn btn-primary mb-1&quot;]/i[@class=&quot;bi bi-pencil-square&quot;]</value>
      <webElementGuid>a101e9bc-c262-4af2-b771-395457830e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='talentTbl']/tr/td/div/div[3]/a/i</value>
      <webElementGuid>dac732fc-7002-46e8-b03b-470baf9e72a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
      <webElementGuid>b55a93e3-bcc4-4174-bac7-6151026425df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionLanguageCollapse--1']/div[2]/i</value>
      <webElementGuid>cf9219d0-017e-4460-8256-e11603f4938b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>fae83bb0-0872-4bc0-b594-545ddcd1db94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
