<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tingkat_text-bottom fa fa-trash</name>
   <tag></tag>
   <elementGuidId>678f52fc-19c9-4abd-891f-826902a1570f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.text-bottom.fa.fa-trash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sectionLanguageBtnDelete--1 >> internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2d01867f-70e0-4456-a958-f7a91fbfe328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-bottom fa fa-trash</value>
      <webElementGuid>128d70d8-8fbc-482d-9b9c-2ec181cddf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionLanguageBtnDelete--1&quot;)/a[@id=&quot;btn&quot;]/i[@class=&quot;text-bottom fa fa-trash&quot;]</value>
      <webElementGuid>a5891ee3-fba5-46e2-9d76-eb00c1110f99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn']/i</value>
      <webElementGuid>b09a33b9-21e3-44c5-830b-f96f3d688773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a/i</value>
      <webElementGuid>118d945e-7049-4e6a-93e0-3948d58db8dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
