<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Posisi_inputOrganizationPosition--1</name>
   <tag></tag>
   <elementGuidId>415d5e55-369d-4dee-80cc-089f882ee1ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputOrganizationPosition--1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputOrganizationPosition--1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#inputOrganizationPosition--1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac147edd-12bd-4ac6-beba-d321ab94c09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-collapse</name>
      <type>Main</type>
      <value>#collapseOrganization--1</value>
      <webElementGuid>9fa583a2-ffd9-4222-a330-37d662bc8c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>autocomplete_off_cv_position</value>
      <webElementGuid>32835444-08e0-4520-bcdf-be936a574783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputOrganizationPosition--1</value>
      <webElementGuid>94efd660-6f65-4ad5-87ec-96d101d7b884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69b67b05-1b4b-4107-a875-a5eb6165d329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>b0532f16-469f-4b62-b99a-9c36e76821f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>
                $('#txtOrganizationPosition--1').text($(this).val()).fadeTo(100, 0.3, function() { $(this).fadeTo(100, 1.0); })
                $('#frame').contents().find('#txtOrganizationPositionFrame--1').text($(this).val()).fadeTo(100, 0.3, function() { $(this).fadeTo(100, 1.0); })
                $('#txtOrganizationPositionFrame--1').text($(this).val()).fadeTo(100, 0.3, function() { $(this).fadeTo(100, 1.0); })
                isOrganizationValueBlank(); autoSave(); validateRequire($(this))</value>
      <webElementGuid>56a38d0a-9559-4563-8cfd-8814759ae411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputOrganizationPosition--1&quot;)</value>
      <webElementGuid>43972324-ef8c-4747-bb53-65633b843c62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputOrganizationPosition--1']</value>
      <webElementGuid>b7e0c552-1dca-4d9e-ba36-bddfd370ad42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOrganization--1']/div[2]/div[2]/input</value>
      <webElementGuid>d334f885-53c9-4cf0-8bd6-2a8ea1222280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>8bbfc705-dfa9-4d90-9226-046931e0ce98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputOrganizationPosition--1' and @type = 'text']</value>
      <webElementGuid>c45eee1e-33ce-49c1-aa79-338b247654b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
