<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_DeveloperApplication Developer Jr.Application Developer Sr.Developer InternshipWeb Developer (intern)System DeveloperSoftware DeveloperWeb DeveloperArxr Developer InternJunior Java DeveloperSofware DeveloperIt Develop</name>
   <tag></tag>
   <elementGuidId>def55180-8a32-4b60-ac6c-becf7661df5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-searchJob-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchJob-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DeveloperApplication Developer Jr.Application Developer Sr.Developer InternshipW&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>1addedb8-22cc-4cd6-b08a-8130c550652b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>feed8a78-3ec6-4ae9-8b7e-1308dca69997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>404ec9f4-120e-431e-be1c-7bb3140a5654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchJob-results</value>
      <webElementGuid>14dde3de-51d3-43dd-ae22-df6a68dde286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>594d7446-d3d5-43ab-8550-fab11e0cdb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e91bcaa0-3a0c-479f-acbb-0cbcaaacd73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DeveloperApplication Developer Jr.Application Developer Sr.Developer InternshipWeb Developer (intern)System DeveloperSoftware DeveloperWeb DeveloperAr/xr Developer InternJunior Java DeveloperSofware DeveloperIt DeveloperPhp Backend Developer InternLaravel Web Developer FreelancerBackend DeveloperWeb Developer InternOdoo Developer JuniorBackend Web Developer InternFrontend DeveloperWeb Developer InternshipBack End Developer InternshipTutor Mobile DeveloperFull Stack DeveloperFullstack Web DeveloperIt (backend Developer)Back-end Developer InternFront End DeveloperMobile &amp; Cloud DeveloperProject Manager &amp; Web Developer (freelance)Backend Developer FreelancerIot DeveloperIot Developer InternJunior Application DeveloperIt Pega DeveloperWeb Developer FreelanceFront-end Developer InternshipBack End DeveloperSoftware Developer (magang)Front-end DeveloperIt Developer StaffApplication Developer Jr./studentIntership Frontend DeveloperApplication DeveloperFrontend Developer (internship)Fullstack DeveloperFreelance Web DeveloperStaff Intern It - Web DeveloperRpa Developer InternshipWebsite DeveloperBack End Developer (Internship)Android Developer InternshipInformation Technology Administrator Officer, Graphic Design, Web DeveloperMagang (Back End Web Developer)Mobile DeveloperFull-stack DeveloperFull-Stack Developer InternJava DeveloperJunior Android DeveloperUI/UX Developer (Magang)Backend Web DeveloperFreelance WordPress DeveloperWebsite Developer InternInternship as Android DeveloperInternship as Web DeveloperApplication Developer FrontEnd Android developerParticipant at Baparekraf Developer DayBack-End DeveloperInternship Full Stack Web DeveloperInternship DeveloperIT Intern Support DeveloperFullstack Developer InternAplication DeveloperDeveloper Web Pembukuan LogistikFrontend developer Full-Stack Developer (Internship)Bootcamp Fullstack .Net DeveloperWeb Developer (Internship)Freelance Etl DeveloperIoT Thingworx DeveloperSoftware Developer InternshipFull Stack developer Application Developer JuniorMagang Web DeveloperFrontend Web DeveloperBackend Developer (Magang)Magang sebagai Front-end Web DeveloperWeb Developer IntersipAkademi Fullstack Web DeveloperJr. Frontend DeveloperFront-End Web DeveloperWebsite Developer / Website MaintenanceJunior DeveloperFull Stack Web Developer (Internship)Angular Developer dan Quality Assurance (Manual Test)Full-stack Developer InternshipPart-time Mobile DeveloperFrontend Developer InternSoftware Developer InternMobile Apps DeveloperInternship Web DeveloperWeb Developer Jr.Wordpress Developer &amp; SEO StaffAndroid Developer InternFront End Developer &amp; Flutter Mobile DeveloperInformation Technology Web DeveloperIT Support &amp; Web DeveloperWeb developer (magang)Web Developer &amp; Public Relations (Fulltime Internship)Senior Back-End Developer - OperationsReact Web Developer (ID Camp Schoolarship)Android DeveloperFreelance Team Buddy Frontend DeveloperFull stack Web Developer InternMOBILE APPLICATION DEVELOPER (INTERNSHIP)Application Developer Jr. (Magang)UI/UX Designer &amp; Frontend Developer - Student InternUI/UX Designer &amp; Frontend Developer - Student ContractIntern - Full Stack DeveloperWeb Developer Magang.Net DeveloperRPA DeveloperTHL Web Developer Junior Application Developer InternJunior App DeveloperFront End Developer Junior Backend DeveloperFrontend developer &amp; UIUX internFullstack Web Developer (intern)Frontend Web Developer Frontend Web Developer (intern)Full Stack Developer MSIB InternshipFrontend Developer InternshipSoftware Developer &amp; Security TesterDesktop DeveloperDesktop Developer InternTelco Developer InternAppication Developer Appication DeveloperProject-Based Intern : Mobile Apps Developer Virtual  Internship ExperienceProject-Based Intern : Full Stack Developer Virtual Internship  Experience Wordpress Web DeveloperFull-Stack Web DeveloperBack end developer OJT - Fullstack DeveloperProject-Based Intern: Backend Developer Virtual Internship ExperienceProject-Based Intern: Front End Developer Virtual Internship ExperienceProject-Based Intern: Fullstack Developer Virtual Internship ExperiencePelatihan Android Developer Android Developer (Intern)Web Developer (Freelance)Full Stack Developer (Freelance)Intern Back End DeveloperFlutter Mobile Developerjunior software developerGame Developer Fullstack Developer InternshipMobile Developer InternshipiOS DeveloperMobile App Developer InternshipIt Developer Buisness Process Automation(MAGANG) Website DeveloperWeb Developer Fullstack Developer (FreelanceAI Developer InternMagang Full-Stack Web DeveloperStaff IT &amp; Web DeveloperApprentice Web DeveloperiOS Developer, UI/UX DesignerFrontend Developer &amp; Ui/ux DesignerWed DeveloperDeveloper Mobile Banking InternFreelance Outsystems DeveloperBack-End Developer (Internship)Front-End Developer (Internship)Front-End Mobile App Developer (Campus Thesis Final Project : Mangkas App, a Barbershop Online Booking)WordPress DeveloperDeveloper Application JuniorAppplication Developer JrProject Based Full Stack DeveloperAplication Developer JrOdoo DeveloperFullstack Web developer  InternApplication Developer JrDeveloper Fullstack &amp; IT SupportJunior Frontend DeveloperJunior Application Developer .NET Developer &amp; Quality AssuranceFront End Web Developer InternIT Support dan Web Developer</value>
      <webElementGuid>158e2b13-c7dd-4bd7-a390-3c57e997d0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchJob-results&quot;)</value>
      <webElementGuid>d64e4c97-603c-48f3-996c-60f497ede072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-searchJob-results']</value>
      <webElementGuid>4f07e705-c17a-447c-8bf7-17980aae00fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::ul[1]</value>
      <webElementGuid>4f7bdb56-0d11-4fb7-b9be-83a44e05b1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>faeed4c5-dc4d-409a-98b2-d4b3a17fe59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-searchJob-results' and (text() = 'DeveloperApplication Developer Jr.Application Developer Sr.Developer InternshipWeb Developer (intern)System DeveloperSoftware DeveloperWeb DeveloperAr/xr Developer InternJunior Java DeveloperSofware DeveloperIt DeveloperPhp Backend Developer InternLaravel Web Developer FreelancerBackend DeveloperWeb Developer InternOdoo Developer JuniorBackend Web Developer InternFrontend DeveloperWeb Developer InternshipBack End Developer InternshipTutor Mobile DeveloperFull Stack DeveloperFullstack Web DeveloperIt (backend Developer)Back-end Developer InternFront End DeveloperMobile &amp; Cloud DeveloperProject Manager &amp; Web Developer (freelance)Backend Developer FreelancerIot DeveloperIot Developer InternJunior Application DeveloperIt Pega DeveloperWeb Developer FreelanceFront-end Developer InternshipBack End DeveloperSoftware Developer (magang)Front-end DeveloperIt Developer StaffApplication Developer Jr./studentIntership Frontend DeveloperApplication DeveloperFrontend Developer (internship)Fullstack DeveloperFreelance Web DeveloperStaff Intern It - Web DeveloperRpa Developer InternshipWebsite DeveloperBack End Developer (Internship)Android Developer InternshipInformation Technology Administrator Officer, Graphic Design, Web DeveloperMagang (Back End Web Developer)Mobile DeveloperFull-stack DeveloperFull-Stack Developer InternJava DeveloperJunior Android DeveloperUI/UX Developer (Magang)Backend Web DeveloperFreelance WordPress DeveloperWebsite Developer InternInternship as Android DeveloperInternship as Web DeveloperApplication Developer FrontEnd Android developerParticipant at Baparekraf Developer DayBack-End DeveloperInternship Full Stack Web DeveloperInternship DeveloperIT Intern Support DeveloperFullstack Developer InternAplication DeveloperDeveloper Web Pembukuan LogistikFrontend developer Full-Stack Developer (Internship)Bootcamp Fullstack .Net DeveloperWeb Developer (Internship)Freelance Etl DeveloperIoT Thingworx DeveloperSoftware Developer InternshipFull Stack developer Application Developer JuniorMagang Web DeveloperFrontend Web DeveloperBackend Developer (Magang)Magang sebagai Front-end Web DeveloperWeb Developer IntersipAkademi Fullstack Web DeveloperJr. Frontend DeveloperFront-End Web DeveloperWebsite Developer / Website MaintenanceJunior DeveloperFull Stack Web Developer (Internship)Angular Developer dan Quality Assurance (Manual Test)Full-stack Developer InternshipPart-time Mobile DeveloperFrontend Developer InternSoftware Developer InternMobile Apps DeveloperInternship Web DeveloperWeb Developer Jr.Wordpress Developer &amp; SEO StaffAndroid Developer InternFront End Developer &amp; Flutter Mobile DeveloperInformation Technology Web DeveloperIT Support &amp; Web DeveloperWeb developer (magang)Web Developer &amp; Public Relations (Fulltime Internship)Senior Back-End Developer - OperationsReact Web Developer (ID Camp Schoolarship)Android DeveloperFreelance Team Buddy Frontend DeveloperFull stack Web Developer InternMOBILE APPLICATION DEVELOPER (INTERNSHIP)Application Developer Jr. (Magang)UI/UX Designer &amp; Frontend Developer - Student InternUI/UX Designer &amp; Frontend Developer - Student ContractIntern - Full Stack DeveloperWeb Developer Magang.Net DeveloperRPA DeveloperTHL Web Developer Junior Application Developer InternJunior App DeveloperFront End Developer Junior Backend DeveloperFrontend developer &amp; UIUX internFullstack Web Developer (intern)Frontend Web Developer Frontend Web Developer (intern)Full Stack Developer MSIB InternshipFrontend Developer InternshipSoftware Developer &amp; Security TesterDesktop DeveloperDesktop Developer InternTelco Developer InternAppication Developer Appication DeveloperProject-Based Intern : Mobile Apps Developer Virtual  Internship ExperienceProject-Based Intern : Full Stack Developer Virtual Internship  Experience Wordpress Web DeveloperFull-Stack Web DeveloperBack end developer OJT - Fullstack DeveloperProject-Based Intern: Backend Developer Virtual Internship ExperienceProject-Based Intern: Front End Developer Virtual Internship ExperienceProject-Based Intern: Fullstack Developer Virtual Internship ExperiencePelatihan Android Developer Android Developer (Intern)Web Developer (Freelance)Full Stack Developer (Freelance)Intern Back End DeveloperFlutter Mobile Developerjunior software developerGame Developer Fullstack Developer InternshipMobile Developer InternshipiOS DeveloperMobile App Developer InternshipIt Developer Buisness Process Automation(MAGANG) Website DeveloperWeb Developer Fullstack Developer (FreelanceAI Developer InternMagang Full-Stack Web DeveloperStaff IT &amp; Web DeveloperApprentice Web DeveloperiOS Developer, UI/UX DesignerFrontend Developer &amp; Ui/ux DesignerWed DeveloperDeveloper Mobile Banking InternFreelance Outsystems DeveloperBack-End Developer (Internship)Front-End Developer (Internship)Front-End Mobile App Developer (Campus Thesis Final Project : Mangkas App, a Barbershop Online Booking)WordPress DeveloperDeveloper Application JuniorAppplication Developer JrProject Based Full Stack DeveloperAplication Developer JrOdoo DeveloperFullstack Web developer  InternApplication Developer JrDeveloper Fullstack &amp; IT SupportJunior Frontend DeveloperJunior Application Developer .NET Developer &amp; Quality AssuranceFront End Web Developer InternIT Support dan Web Developer' or . = 'DeveloperApplication Developer Jr.Application Developer Sr.Developer InternshipWeb Developer (intern)System DeveloperSoftware DeveloperWeb DeveloperAr/xr Developer InternJunior Java DeveloperSofware DeveloperIt DeveloperPhp Backend Developer InternLaravel Web Developer FreelancerBackend DeveloperWeb Developer InternOdoo Developer JuniorBackend Web Developer InternFrontend DeveloperWeb Developer InternshipBack End Developer InternshipTutor Mobile DeveloperFull Stack DeveloperFullstack Web DeveloperIt (backend Developer)Back-end Developer InternFront End DeveloperMobile &amp; Cloud DeveloperProject Manager &amp; Web Developer (freelance)Backend Developer FreelancerIot DeveloperIot Developer InternJunior Application DeveloperIt Pega DeveloperWeb Developer FreelanceFront-end Developer InternshipBack End DeveloperSoftware Developer (magang)Front-end DeveloperIt Developer StaffApplication Developer Jr./studentIntership Frontend DeveloperApplication DeveloperFrontend Developer (internship)Fullstack DeveloperFreelance Web DeveloperStaff Intern It - Web DeveloperRpa Developer InternshipWebsite DeveloperBack End Developer (Internship)Android Developer InternshipInformation Technology Administrator Officer, Graphic Design, Web DeveloperMagang (Back End Web Developer)Mobile DeveloperFull-stack DeveloperFull-Stack Developer InternJava DeveloperJunior Android DeveloperUI/UX Developer (Magang)Backend Web DeveloperFreelance WordPress DeveloperWebsite Developer InternInternship as Android DeveloperInternship as Web DeveloperApplication Developer FrontEnd Android developerParticipant at Baparekraf Developer DayBack-End DeveloperInternship Full Stack Web DeveloperInternship DeveloperIT Intern Support DeveloperFullstack Developer InternAplication DeveloperDeveloper Web Pembukuan LogistikFrontend developer Full-Stack Developer (Internship)Bootcamp Fullstack .Net DeveloperWeb Developer (Internship)Freelance Etl DeveloperIoT Thingworx DeveloperSoftware Developer InternshipFull Stack developer Application Developer JuniorMagang Web DeveloperFrontend Web DeveloperBackend Developer (Magang)Magang sebagai Front-end Web DeveloperWeb Developer IntersipAkademi Fullstack Web DeveloperJr. Frontend DeveloperFront-End Web DeveloperWebsite Developer / Website MaintenanceJunior DeveloperFull Stack Web Developer (Internship)Angular Developer dan Quality Assurance (Manual Test)Full-stack Developer InternshipPart-time Mobile DeveloperFrontend Developer InternSoftware Developer InternMobile Apps DeveloperInternship Web DeveloperWeb Developer Jr.Wordpress Developer &amp; SEO StaffAndroid Developer InternFront End Developer &amp; Flutter Mobile DeveloperInformation Technology Web DeveloperIT Support &amp; Web DeveloperWeb developer (magang)Web Developer &amp; Public Relations (Fulltime Internship)Senior Back-End Developer - OperationsReact Web Developer (ID Camp Schoolarship)Android DeveloperFreelance Team Buddy Frontend DeveloperFull stack Web Developer InternMOBILE APPLICATION DEVELOPER (INTERNSHIP)Application Developer Jr. (Magang)UI/UX Designer &amp; Frontend Developer - Student InternUI/UX Designer &amp; Frontend Developer - Student ContractIntern - Full Stack DeveloperWeb Developer Magang.Net DeveloperRPA DeveloperTHL Web Developer Junior Application Developer InternJunior App DeveloperFront End Developer Junior Backend DeveloperFrontend developer &amp; UIUX internFullstack Web Developer (intern)Frontend Web Developer Frontend Web Developer (intern)Full Stack Developer MSIB InternshipFrontend Developer InternshipSoftware Developer &amp; Security TesterDesktop DeveloperDesktop Developer InternTelco Developer InternAppication Developer Appication DeveloperProject-Based Intern : Mobile Apps Developer Virtual  Internship ExperienceProject-Based Intern : Full Stack Developer Virtual Internship  Experience Wordpress Web DeveloperFull-Stack Web DeveloperBack end developer OJT - Fullstack DeveloperProject-Based Intern: Backend Developer Virtual Internship ExperienceProject-Based Intern: Front End Developer Virtual Internship ExperienceProject-Based Intern: Fullstack Developer Virtual Internship ExperiencePelatihan Android Developer Android Developer (Intern)Web Developer (Freelance)Full Stack Developer (Freelance)Intern Back End DeveloperFlutter Mobile Developerjunior software developerGame Developer Fullstack Developer InternshipMobile Developer InternshipiOS DeveloperMobile App Developer InternshipIt Developer Buisness Process Automation(MAGANG) Website DeveloperWeb Developer Fullstack Developer (FreelanceAI Developer InternMagang Full-Stack Web DeveloperStaff IT &amp; Web DeveloperApprentice Web DeveloperiOS Developer, UI/UX DesignerFrontend Developer &amp; Ui/ux DesignerWed DeveloperDeveloper Mobile Banking InternFreelance Outsystems DeveloperBack-End Developer (Internship)Front-End Developer (Internship)Front-End Mobile App Developer (Campus Thesis Final Project : Mangkas App, a Barbershop Online Booking)WordPress DeveloperDeveloper Application JuniorAppplication Developer JrProject Based Full Stack DeveloperAplication Developer JrOdoo DeveloperFullstack Web developer  InternApplication Developer JrDeveloper Fullstack &amp; IT SupportJunior Frontend DeveloperJunior Application Developer .NET Developer &amp; Quality AssuranceFront End Web Developer InternIT Support dan Web Developer')]</value>
      <webElementGuid>d1525ff4-40e6-4556-bda8-cda892f89df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
