<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kapanpun_timeInterval</name>
   <tag></tag>
   <elementGuidId>c98f81fc-4274-476e-bc66-4e26fb9ef20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filterAnytime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filterAnytime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Kapanpun&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f9c208e-bda9-4c6e-8a3c-28a3e60af9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>390961a3-8c74-44f6-8930-c581f832f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterAnytime</value>
      <webElementGuid>0a5815a6-a221-4372-bd17-4415dd377428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timeInterval</value>
      <webElementGuid>2cd16bb0-3b35-4095-8685-801ee59a614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterAnytime&quot;)</value>
      <webElementGuid>11fb0d14-2672-40c8-bb60-b96fb58f8b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filterAnytime']</value>
      <webElementGuid>580b9ab4-863f-4ec4-8b75-7a5be5e0be95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>a6d5e989-b79e-4d75-bc3d-2f5caacef288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'filterAnytime' and @name = 'timeInterval']</value>
      <webElementGuid>2952092a-823e-4151-adeb-a069f7da9889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
